### ISSUE TITLE
Example configuration does not work?

### ISSUE THREAD

**Issue by knayet** [chonton/touch-maven-plugin#1]
Hi there, I'm having some issues getting this plugin working.

The "Create a file" configuration example gives me this error:
The parameters 'files' for goal org.honton.chas:touch-maven-plugin:0.0.1:touch are missing or invalid

So I changed it to:
```
    <configuration>
      <modificationTime>${maven.build.timestamp}</modificationTime>
      <files><directory>path/to/create</directory><includes><include>.gitignore</include></includes></files>
    </configuration>
```
Which gets me further, to the following message:
java.nio.file.NoSuchFileException: path/to/create

Hmmm....... I thought it should create the path? Anyways, let's try to use a path that already exists:
```
    <configuration>
      <modificationTime>${maven.build.timestamp}</modificationTime>
      <files><directory>${project.build.outputDirectory}</directory><includes><include>.gitignore</include></includes></files>
    </configuration>
```
Now it's:
Caused by: java.lang.NullPointerException
    at java.nio.file.Files.provider (Files.java:101)
    at java.nio.file.Files.createDirectory (Files.java:690)

Somehow it still wants to create the directory?

I'm at a loss, and I've stopped trying by this point,
Hope you are still interested in your project and wish to shine a light on my troubles!

**Comment by chonton** [comment]
Thanks for the report.  Your example helped me pinpoint an issue.  Please try 0.0.2

**Comment by knayet** [comment]
Hi, thanks for the swift reply!

I tried it out, and happy to report it works, so thanks again!

On a sidenote, I used <version> directly inside <plugins><plugin> 
instead of <pluginManagement><plugins><plugin> to reduce some cruft in 
the pom.xml.
